/** @import {Actor} from "@client/documents/actor.mjs" */
/** @import {Roll} from "@client/dice/roll.mjs" */

/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @import {Actor} from "@client/documents/actor.mjs"
 * @extends {Actor}
 */
export class RtRActor extends Actor {
  /** @override */
  prepareData() {
    // Prepare data for the actor. Calling the super version of this executes
    // the following, in order: data reset (to clear active effects),
    // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
    // prepareDerivedData().
    super.prepareData();
  }

  /** @override */
  prepareBaseData() {
    // Data modifications in this step occur before processing embedded
    // documents or derived data.
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    const actorData = this;
    const flags = actorData.flags.reclaimtherealm || {};
  }

  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }

  /**
   * D20 Test
   * @param {*} options 
   */
  d20Test(options) {
    let die = 'd20';
    if (options.advantage && !options.disadvantage) {
        die = '2d20kh';
    } if (options.disadvantage && !options.advantage) {
        die = '2d20kl';
    }

    let d20TestBonuses = '';
    if (this.getRollData().d20Test !== 0) {
      d20TestBonuses = ' +@d20Test'
    }
    options.extraDice = options.extraDice ? options.extraDice : '';

    if (this._hasStatusEffect('DISTRACTED')) {
      d20TestBonuses = d20TestBonuses + ' -2';
    }

    let formula=`${die}${options.extraDice}${d20TestBonuses}${options.bonus}`;
    this.roll(formula, options);
  }

  /**
   * Attack Test, any interactions that modifies any attack happens here.
   * @param {*} options 
   * @protected
   */
  attackTest(options) {
    if (this._hasStatusEffect('FRIGHTENED I')) {
      options.disadvantage = true;
    }
    if (this._hasStatusEffect('CURSED I')) {
      options.extraDice = options.extraDice ? options.extraDice + ' -d4' : ' -d4';
    }
    if (this._hasStatusEffect('BLESS I')) {
      options.extraDice = options.extraDice ? options.extraDice + ' +d4' : ' +d4';
    }

    this.d20Test(options);
  }

  /**
   * Meele Martial Attack
   * @param {*} options 
   */
  meleeMartialAttack(options) {
    options.type = 'MELEE MARTIAL ATTACK';
    options.bonus = options.bonus ? options.bonus + ' +@meleeMartialAttack' : ' +@meleeMartialAttack';
    if (this._hasStatusEffect('PRONE')) {
      options.disadvantage = true;
    }
    this.attackTest(options);
  }

  /**
   * Ranged Martial Attack
   * @param {*} options 
   */
  rangedMartialAttack(options) {
    options.type = 'RANGED MARTIAL ATTACK';
    options.bonus = options.bonus ? options.bonus + ' +@rangedMartialAttack' : ' +@rangedMartialAttack';
    this.attackTest(options);
  }

  /**
   * Meele Spell Attack
   * @param {*} options 
   */
  meleeSpellAttack(options) {
    options.type = 'MELEE SPELL ATTACK';
    options.bonus = options.bonus ? options.bonus + ' +@meleeSpellAttack' : ' +@meleeSpellAttack';
    if (this._hasStatusEffect('PRONE')) {
      options.disadvantage = true;
    }
    this.attackTest(options);
  }

  /**
   * Ranged Spell Attack
   * @param {*} options 
   */
  rangedSpellAttack(options) {
    options.type = 'RANGED SPELL ATTACK';
    options.bonus = options.bonus ? options.bonus + ' +@rangedSpellAttack' : ' +@rangedSpellAttack';
    this.attackTest(options);
  }

  /**
   * Martial Test
   * @param {*} options 
   */
  martialTest(options) {
    if (this._hasStatusEffect('FRIGHTENED I')) {
      options.disadvantage = true;
    }
    if (this._hasStatusEffect('CURSED I')) {
      options.extraDice = options.extraDice ? options.extraDice + ' -d4' : ' -d4';
    }
    if (this._hasStatusEffect('BLESS I')) {
      options.extraDice = options.extraDice ? options.extraDice + ' +d4' : ' +d4';
    }
    options.type = 'MARTIAL TEST';
    options.bonus = options.bonus ? options.bonus + ' +@martialTest' : ' +@martialTest';
    options.bonus =  options.bonus + this._getAttributeRollBonus(options.attribute);

    this.d20Test(options);
  }

   /**
   * Spell Test
   * @param {*} options 
   */
  spellTest(options) {
    if (this._hasStatusEffect('FRIGHTENED I')) {
      options.disadvantage = true;
    }
    if (this._hasStatusEffect('CURSED I')) {
      options.extraDice = options.extraDice ? options.extraDice + ' -d4' : ' -d4';
    }
    if (this._hasStatusEffect('BLESS I')) {
      options.extraDice = options.extraDice ? options.extraDice + ' +d4' : ' +d4';
    }
    attributeTestData = this._getAttributeRollBonus(options.attribute);
    options.type = 'SPELL TEST';
    options.bonus = options.bonus ? options.bonus + ' +@spellTest' : ' +@spellTest';
    options.bonus =  options.bonus + this._getAttributeRollBonus(options.attribute);

    this.d20Test(options);
  }

  /**
   * Attribute Test
   * @param {*} options 
   */
  attributeTest(options) {
    let attributeTestData = this._getAttributeRollBonus(options.attribute);
    options.bonus = options.bonus ? options.bonus + attributeTestData.rollData : attributeTestData.rollData;

    if (!options.type) {
      options.type = attributeTestData.rollType + ' ATTRIBUTE TEST';
    } else {
      options.type = attributeTestData.rollType + ' ' + options.type;
    }

    if (this._hasStatusEffect('INTOXICATED') && ( options.attribute === 'agi' || options.attribute === 'per')) {
      options.bonus = options.bonus + ' -5';
    }
    if (options.attribute === 'per' && this._hasStatusEffect('DISTRACTED')) {
      options.disadvantage = true;
    }
    if (options.attribute === 'agi' && this._hasStatusEffect('HASTE I')) {
      options.advantage = true;
    }
    if (this._hasStatusEffect('FOCUSED') && (options.attribute === 'int' || options.attribute === 'per')) {
      options.advantage = true;
    }

    this.d20Test(options);
  }

  /**
   * Skill Test
   * @param {*} options 
   */
  skillTest(options) {
    let skillTestData = this._getSkillRollBonus(options.skill);
    options.bonus =  options.bonus ? options.bonus + skillTestData.rollData : skillTestData.rollData;
    options.type = skillTestData.rollType + ' SKILL TEST';
    this.attributeTest(options);
  }

  /**
   * Save Test
   * @param {*} options
   * @protected
   */
  saveTest(options) {
    let saveRollData = this._getSaveRollBonus(options.save);
    options.bonus =  options.bonus ? options.bonus + saveRollData.rollData : saveRollData.rollData;
    options.type = saveRollData.rollType;

    if (this._hasStatusEffect('VULNURABLE I')) {
      options.extraDice = options.extraDice ? options.extraDice + ' -d4' : ' -d4';
    }
    if (this._hasStatusEffect('PROTECTION I')) {
      options.extraDice = options.extraDice ? options.extraDice + ' +d4' : ' +d4';
    }

    this.d20Test(options);
  }

  /**
   * @param {string} formula
   * @param {*} options
   * @returns {Roll} roll object
   * @protected
   */
  async roll(formula, options) {
    let label = options.type;
    if (options.advantage && !options.disadvantage) {
        label = '<span style="color:green">ADVANTAGE ' + options.type + '</span>';
    } if (options.disadvantage && !options.advantage) {
        label = '<span style="color:red">DISADVANTAGE ' + options.type + '</span>';
    }
    let roll = new Roll(formula, this.getRollData());
    await roll.toMessage({
      speaker: ChatMessage.getSpeaker({ actor: this }),
      flavor: label,
      rollMode: game.settings.get('core', 'rollMode'),
    });
    return roll;
  }

  /**
   * Handle everything that happens on the start of combat
   */
  async handleOnCombatTrunStart() {
    if (this._hasStatusEffect('BURNING I')) {
      this.roll('d6[fire]', { type: 'BURNING I' }).then(result => {
        let damage = result.terms[0].results[0].result;
        this.applyDamage(damage, 'fire');
      });
    }
    if (this._hasStatusEffect('BLEEDING I')) {
      this.roll('d6[bleed]', { type: 'BLEEDING I' }).then(result => {
        let damage = result.terms[0].results[0].result;
        this.applyDamage(damage, 'bleed');
      });
    }
    if (this._hasStatusEffect('POISON I')) {
      this.roll('d6[poison]', { type: 'POISON I' }).then(result => {
        let damage = result.terms[0].results[0].result;
        this.applyDamage(damage, 'poison');
      });
    }
    if (this._hasStatusEffect('HEALING I')) {
      this.roll('d6[heal]', { type: 'HEALING I' }).then(result => {
        let heal = result.terms[0].results[0].result;
        this.heal(heal);
      });
    }
  }

  /**
   * apply damage to actor
   * @param {number} amount 
   * @param {string} type 
   */
  applyDamage(amount, type) {
    ChatMessage.create({
        speaker: ChatMessage.getSpeaker({ actor: this }),
        content: `${this.name} recieves ${amount} ${type} damage.`,
        style: CONST.CHAT_MESSAGE_STYLES.OOC
    });

    let remainingAmount = amount;
    if (this.system.tempHp > 0) {
      remainingAmount = amount - Math.min(this.system.tempHp, amount);
      let newTempHp = Math.max(0, this.system.tempHp - amount);
      this.update({ "system.tempHp": newTempHp});
    }
    // TODO handle resistances and stuff.
    let newHp = Math.max(0, this.system.hp.value - remainingAmount);
    this.update({ "system.hp.value": newHp});
  }

  /**
   * heal actor
   * @param {number} amount 
   */
  heal(amount) {
    ChatMessage.create({
        speaker: ChatMessage.getSpeaker({ actor: this }),
        content: `${this.name} heals ${amount} HP.`,
        style: CONST.CHAT_MESSAGE_STYLES.OOC
    });

    let newHp = Math.min(this.system.hp.max, this.system.hp.value + amount);
    this.update({ "system.hp.value": newHp});
  }

  /**
   * checks if actor has a status effect
   * @param {string} statusEffectName 
   * @returns true if status effect is active on actor and false if not
   * @private
   */
  _hasStatusEffect(statusEffectName) {
    const existing = this.appliedEffects.find(effect => effect.name === statusEffectName);
    return existing !== undefined;
  }

  /**
   * @param {string} attribute 
   * @returns attribute roll data string
   * @private
   */
  _getAttributeRollBonus(attribute) {
    let foundAttribute = Object.keys(CONFIG.RTR.attributes).find(attributeName => attributeName === attribute);
    if (!foundAttribute) {
      ui.notifications.error(`Attribute ${attribute} not found`, {console: true});
      return {};
    }
    return { rollData: `+@attributes.${foundAttribute}.value`, rollType: foundAttribute.toUpperCase() };
  }

  /**
   * @param {string} skill 
   * @returns skill roll data string
   * @private
   */
  _getSkillRollBonus(skill) {
    let foundSkill = Object.keys(CONFIG.RTR.skills).find(skillname => skillname === skill);
    if (!foundSkill) {
      ui.notifications.error(`Skill ${skill} not found`, {console: true});
      return {};
    }
    if (foundSkill === 'stealth') {
      return { rollData: `+@skills.${foundSkill}.rank-@manoeuvrePenalty`, rollType: foundSkill }; 
    }
    return { rollData: `+@skills.${foundSkill}.rank`, rollType: foundSkill };
  }

  /**
   * @param {string} save 
   * @returns {Object} save roll with roll type label
   * @private
   */
  _getSaveRollBonus(save) {
    switch(save) {
      case 'stability': return { rollData: '+@stabilitySave', rollType: 'STABILITY SAVE'};
      case 'dodge': return { rollData: '+@dodgeSave', rollType: 'DODGE SAVE'};
      case 'toughness': return { rollData: '+@toughnessSave', rollType: 'TOUGHNESS SAVE'};
      case 'willpower': return { rollData: '+@willpowerSave', rollType: 'WILLPOWER SAVE'};
      case 'shieldblock': return { rollData: '+@shieldBlock', rollType: 'SHIELD BLOCK'};
    }
    ui.notifications.error(`Unkown Save ${save}`, {console: true});
    return {};
  }
}
